// ASPICE v4.0 Work Product category index.
// Only the most common output WP IDs are defined here — process plugins
// reference them by ID. The harness uses the category metadata to pick
// sensible file-format expectations for rule-based checks.

export const WP_CATEGORY = Object.freeze({
  PLAN: "01",
  MEETING: "02",
  REPORT: "03",
  DESIGN: "04",
  SPEC: "05",
  TEST: "06",
  REQUEST: "07",
  STRATEGY: "08",
  POLICY: "09",
  PROCESS: "10",
  PRODUCT: "11",
  TOOLS: "12",
  RECORD: "13",
  ISSUE: "14",
  STATUS: "15",
  REPOSITORY: "16",
  VIEW: "17",
  STANDARD: "18",
  TEST_RESULT: "19",
});

export const WORK_PRODUCTS = Object.freeze({
  "01-03": { id: "01-03", name: "Quality plan", category: WP_CATEGORY.PLAN },
  "01-50": { id: "01-50", name: "Project management plan", category: WP_CATEGORY.PLAN },
  "02-00": { id: "02-00", name: "Commitment / agreement", category: WP_CATEGORY.MEETING },
  "02-01": { id: "02-01", name: "Meeting minutes", category: WP_CATEGORY.MEETING },
  "03-03": { id: "03-03", name: "Benchmarking report", category: WP_CATEGORY.REPORT },
  "03-04": { id: "03-04", name: "Acceptance report", category: WP_CATEGORY.REPORT },
  "03-06": { id: "03-06", name: "Process performance report", category: WP_CATEGORY.REPORT },
  "04-02": { id: "04-02", name: "Domain architecture", category: WP_CATEGORY.DESIGN },
  "04-04": { id: "04-04", name: "Software architectural design", category: WP_CATEGORY.DESIGN },
  "04-05": { id: "04-05", name: "Software detailed design", category: WP_CATEGORY.DESIGN },
  "04-06": { id: "04-06", name: "System architectural design", category: WP_CATEGORY.DESIGN },
  "04-07": { id: "04-07", name: "Hardware design", category: WP_CATEGORY.DESIGN },
  "05-02": { id: "05-02", name: "Customer requirements specification", category: WP_CATEGORY.SPEC },
  "07-00": { id: "07-00", name: "Requirement", category: WP_CATEGORY.REQUEST },
  "08-50": { id: "08-50", name: "Test specification", category: WP_CATEGORY.TEST },
  "08-52": { id: "08-52", name: "Test case specification", category: WP_CATEGORY.TEST },
  "08-60": { id: "08-60", name: "Change management plan", category: WP_CATEGORY.STRATEGY },
  "08-61": { id: "08-61", name: "Configuration management plan", category: WP_CATEGORY.STRATEGY },
  "08-62": { id: "08-62", name: "Problem management plan", category: WP_CATEGORY.STRATEGY },
  "09-03": { id: "09-03", name: "Quality policy", category: WP_CATEGORY.POLICY },
  "10-50": { id: "10-50", name: "Problem resolution process", category: WP_CATEGORY.PROCESS },
  "11-03": { id: "11-03", name: "Product release information", category: WP_CATEGORY.PRODUCT },
  "11-04": { id: "11-04", name: "Product release package", category: WP_CATEGORY.PRODUCT },
  "11-05": { id: "11-05", name: "Software unit", category: WP_CATEGORY.PRODUCT },
  "11-06": { id: "11-06", name: "System", category: WP_CATEGORY.PRODUCT },
  "11-07": { id: "11-07", name: "Temporary solution", category: WP_CATEGORY.PRODUCT },
  "13-04": { id: "13-04", name: "Communication record", category: WP_CATEGORY.RECORD },
  "13-05": { id: "13-05", name: "Contract review record", category: WP_CATEGORY.RECORD },
  "13-06": { id: "13-06", name: "Delivery record", category: WP_CATEGORY.RECORD },
  "13-07": { id: "13-07", name: "Problem record", category: WP_CATEGORY.RECORD },
  "13-08": { id: "13-08", name: "Baseline", category: WP_CATEGORY.RECORD },
  "13-09": { id: "13-09", name: "Meeting support record", category: WP_CATEGORY.RECORD },
  "13-10": { id: "13-10", name: "Traceability record", category: WP_CATEGORY.RECORD },
  "13-14": { id: "13-14", name: "Configuration status report", category: WP_CATEGORY.RECORD },
  "13-16": { id: "13-16", name: "Change request", category: WP_CATEGORY.RECORD },
  "13-18": { id: "13-18", name: "Quality record", category: WP_CATEGORY.RECORD },
  "13-19": { id: "13-19", name: "Review record / review evidence", category: WP_CATEGORY.RECORD },
  "13-21": { id: "13-21", name: "Change control record", category: WP_CATEGORY.RECORD },
  "13-22": { id: "13-22", name: "Traceability matrix", category: WP_CATEGORY.RECORD },
  "13-25": { id: "13-25", name: "Verification results", category: WP_CATEGORY.RECORD },
  "13-50": { id: "13-50", name: "Validation results", category: WP_CATEGORY.RECORD },
  "14-02": { id: "14-02", name: "Corrective action register", category: WP_CATEGORY.ISSUE },
  "14-50": { id: "14-50", name: "Stakeholder groups list", category: WP_CATEGORY.ISSUE },
  "14-52": { id: "14-52", name: "Analysis report", category: WP_CATEGORY.ISSUE },
  "15-01": { id: "15-01", name: "Analysis report", category: WP_CATEGORY.STATUS },
  "15-03": { id: "15-03", name: "Project status report", category: WP_CATEGORY.STATUS },
  "15-05": { id: "15-05", name: "Evaluation report", category: WP_CATEGORY.STATUS },
  "15-06": { id: "15-06", name: "Supplier evaluation report", category: WP_CATEGORY.STATUS },
  "15-07": { id: "15-07", name: "Measure/metrics report", category: WP_CATEGORY.STATUS },
  "15-08": { id: "15-08", name: "Process performance report", category: WP_CATEGORY.STATUS },
  "15-16": { id: "15-16", name: "Improvement opportunity", category: WP_CATEGORY.STATUS },
  "16-03": { id: "16-03", name: "Configuration management system / repository", category: WP_CATEGORY.REPOSITORY },
  "17-00": { id: "17-00", name: "Hardware architecture view", category: WP_CATEGORY.VIEW },
  "17-02": { id: "17-02", name: "Build list", category: WP_CATEGORY.VIEW },
  "17-03": { id: "17-03", name: "System requirements", category: WP_CATEGORY.VIEW },
  "17-08": { id: "17-08", name: "Interface requirements", category: WP_CATEGORY.VIEW },
  "17-11": { id: "17-11", name: "Software requirements", category: WP_CATEGORY.VIEW },
  "17-12": { id: "17-12", name: "Hardware requirements", category: WP_CATEGORY.VIEW },
  "17-50": { id: "17-50", name: "Stakeholder requirements", category: WP_CATEGORY.VIEW },
  "18-00": { id: "18-00", name: "Standard", category: WP_CATEGORY.STANDARD },
  "18-06": { id: "18-06", name: "Product release criteria", category: WP_CATEGORY.STANDARD },
  "18-50": { id: "18-50", name: "Validation measures", category: WP_CATEGORY.STANDARD },
  "18-52": { id: "18-52", name: "Acceptance criteria", category: WP_CATEGORY.STANDARD },
  "19-00": { id: "19-00", name: "Test specification", category: WP_CATEGORY.TEST_RESULT },
  "19-01": { id: "19-01", name: "Test plan", category: WP_CATEGORY.TEST_RESULT },
  "19-03": { id: "19-03", name: "Validation plan", category: WP_CATEGORY.TEST_RESULT },
  "19-10": { id: "19-10", name: "Test specification (integration)", category: WP_CATEGORY.TEST_RESULT },
  "19-11": { id: "19-11", name: "Test specification (system)", category: WP_CATEGORY.TEST_RESULT },
  "19-12": { id: "19-12", name: "Unit test specification", category: WP_CATEGORY.TEST_RESULT },
});

export function lookupWorkProduct(id) {
  return WORK_PRODUCTS[id] ?? { id, name: id, category: null };
}
